### ISSUE TITLE
Restoring from a DB Cluster Snapshot does not mention DB instances

### ISSUE THREAD

**Issue by vkatsikaros** [awsdocs/amazon-aurora-user-guide#11]
The [currently latest "Restoring from a DB Cluster Snapshot"](https://github.com/awsdocs/amazon-aurora-user-guide/blob/4b07da7eee3836acbe6b3a8a293649266ec36d71/doc_source/USER_RestoreFromSnapshot.md) explains a lot about restoring from an aurora DB cluster snapshot, but omits one important detail (at least for the CLI): `aws rds restore-db-cluster-from-snapshot` restores only the cluster, but no instances.

This is obscurely documented in [some](https://forums.aws.amazon.com/thread.jspa?messageID=688727) [places](https://stackoverflow.com/questions/41039717/aws-aurora-how-to-restore-a-db-cluster-snapshot-via-aws-cli) but I can't find it documented in the official documentation.

I experience the confusion myself, and indeed after running `aws rds restore-db-cluster-from-snapshot`, one needs to run `aws rds create-db-instance`.

**Comment by claytran** [comment]
This has been fixed in the documentation:
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_RestoreFromSnapshot.html#USER_RestoreFromSnapshot.Restoring
