### ISSUE TITLE
unable to add IAM role to aurora 

### ISSUE THREAD

**Issue by venkateshkb** [awsdocs/amazon-aurora-user-guide#18]
when calling the AddRoleToDBCluster operation: You currently can't add a role to Aurora Serverless DB Cluster    --- Im getting this error

**Comment by randyurbano** [comment]
Thanks for your feedback, and sorry about the delay in responding.

See the limitations for Aurora Serverless in this topic:

Limitations of Aurora Serverless
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations

Aurora Serverless doesn't support the features that require adding a role, such as S3 integration. So, adding an IAM role doesn't apply to Aurora Serverless DB clusters.

**Comment by adnan-iqbal-ch** [comment]
is there a way to support aws_s3.query_export_to_s3 on Aurora Serverless, its not possible because of above limitation. Is there any alternative approach available for Aurora Serverless to move data to s3 or change capture via trigger to downstream?

**Comment by hebbsThakral** [comment]
Did you find a solution? I can only think about having a trigger on multiple tables to populate a changes table (maybe with an ID and json field). The triggers insert the changes to this table. Then (sadly) poll the changes changes table with a "select ... for update" (so you can do this in parallel if you want to) and delete any change after successfully invoking the S3 or lambda function from your application server.

**Comment by adnan-iqbal-ch** [comment]
I have done by logging a message in logs and triggering a lambda from cloudwatch logs with pattern and pulling data from aurora on log event.

**Comment by hebbsThakral** [comment]
Great idea - how did you manage to log a message into the Aurora logs?
