### ISSUE TITLE
Do Fault Injection Queries Work in a Cross-Region Replication Setup?

### ISSUE THREAD

**Issue by Jeeppler** [awsdocs/amazon-aurora-user-guide#2]
Do the queries/commands listed in the ["Testing Amazon Aurora Using Fault Injection Queries"](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Managing.FaultInjectionQueries.html) work in a cross region replication setup. 

In addition, it would be nice to add an example which explains how and when to use the `ALTER SYSTEM CRASH [ INSTANCE | DISPATCHER | NODE ];` command or the [`failover-db-cluster`](https://docs.aws.amazon.com/cli/latest/reference/rds/failover-db-cluster.html) CLI command. 

In general it would be nice have more examples based on scenarios in the "Testing Amazon Aurora Using Fault Injection Queries". This is a very important topic for disaster recovery testing and planing.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
