### ISSUE TITLE
Using Amazon Aurora Auto Scaling with Aurora Replicas - Innacurate Statements

### ISSUE THREAD

**Issue by icj217** [awsdocs/amazon-aurora-user-guide#22]
In [/doc_source/Aurora.Integrating.AutoScaling.md](https://github.com/awsdocs/amazon-aurora-user-guide/blob/master/doc_source/Aurora.Integrating.AutoScaling.md#before-you-begin) it states that:
> Before you can use Aurora Auto Scaling with an Aurora DB cluster, you must first create an Aurora DB cluster with a primary instance and at least one Aurora Replica. Although Aurora Auto Scaling manages Aurora Replicas, the Aurora DB cluster must start with at least one Aurora Replica

This does not seem to be the case. I can do the following and watch an Aurora Replica get spun up automatically:
1. Create an Aurora cluster
2. Add a primary instance to the cluster
3. Add an Auto Scaling policy with minimum capacity = 1

Whereas if I do the following, an Aurora Replica never gets created:
1. Create Aurora cluster
2. Add an Auto Scaling policy with minimum capacity = 1
3. add a primary instance to the cluster

It seems more accurate to say that **only a primary instance is needed**. It also seems like the second scenario where the policy is created before the cluster has any instances should not be possible. The API should prevent the policy from being created.

**Comment by claytran** [comment]
I confirmed this by adding a scaling policy with a minimum number of connections =1 to a DB cluster with no reader instances. An autoscaling reader instance was created immediately, even though there was a note in the console saying that the cluster had no readers.

**Comment by claytran** [comment]
message was:
March 7th 2023, 3:22:11 pm UTC-5 (local) |   | InProgress | Adding 1 read replica(s). | Adding  read replica(s)  application-autoscaling-<long alphanumeric>. Waiting  for read replica(s) to be added by rds.

**Comment by claytran** [comment]
changed text to read:

Before you can use Aurora Auto Scaling with an Aurora DB cluster, you must first create an Aurora DB cluster with a primary DB instance. For more information about creating an Aurora DB cluster,see [Creating an Amazon Aurora DB cluster](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.CreateInstance.html).

Aurora Auto Scaling only scales a DB cluster if the DB cluster is in the available state.
