### ISSUE TITLE
\gset not supported in Aurora engineVersion 10.11

### ISSUE THREAD

**Issue by itarano** [awsdocs/amazon-aurora-user-guide#32]
[Documentation](https://github.com/awsdocs/amazon-aurora-user-guide/blob/main/doc_source/AuroraPostgreSQL.Migrating.md#importing-amazon-s3-data-into-an-aurora-postgresql-db-cluster):
"To import from Amazon S3 into Aurora PostgreSQL, your database must be running PostgreSQL version 10.7 or later."
and
"psql=> SELECT aws_commons.create_s3_uri(
   'sample-bucket',
   'sample-filepath',
   'us-west-2'
) AS s3_uri_1 \gset"

Problem: 
Invalid command \gset. Try \? for help.

**Comment by itarano** [comment]
Documentation url updated (master -> main)

**Comment by ardentperf** [comment]
I just did a quick test, and it worked for me:

    aurora-10.11-2.4.4 rw root@db1=> SELECT 'hello' AS var1, 10 AS var2 \gset
    Time: 0.488 ms
    
    aurora-10.11-2.4.4 rw root@db1=> \echo :var1 :var2 
    hello 10

Maybe check what version of the psql client you're using?

**Comment by randyurbano** [comment]
Thanks for the feedback. I'm closing this issue based on the previous comment.
