### ISSUE TITLE
Missing column entry

### ISSUE THREAD

**Issue by mini-turtle** [awsdocs/amazon-aurora-user-guide#40]
In the table at the bottom of the page, under the field: Max. bandwidth (mbps) of local storage
There is no value for this row (just a "--"). 
db.r3.8xlarge	32	104	244	—	10 Gbps
Why is this?

**Comment by lanceashdown66** [comment]
Hi. Thank you for your pull request. I'm sorry for the delay. The EC2 doc says the following: "The i2.8xlarge, c3.8xlarge, and r3.8xlarge instances do not have dedicated EBS bandwidth and therefore do not offer EBS optimization. On these instances, network traffic and Amazon EBS traffic share the same 10-gigabit network interface."

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html

I will add a note below the table saying the following:

"The r3.8xlarge instance doesn't have dedicated EBS bandwidth and therefore doesn't offer EBS optimization. On this instance, network traffic and Amazon EBS traffic share the same 10-gigabit network interface."

The update will appear the next time we refresh the doc. 

Thanks, 
Lance
