### ISSUE TITLE
Fix/Remove incomplete and useless recommendation

### ISSUE THREAD

**Issue by damleak** [awsdocs/amazon-aurora-user-guide#45]
Most of the information in section `Using the Java client library for Data API` of the document at https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html doesn't work or is not implemented. It is misguiding and users spend a lot of time figuring out what went wrong. I feel like it is not implemented completely and the documentation is not updated properly. For example `withParameter` works but, not `withParam` as it appears in the documentation.

**Comment by randyurbano** [comment]
Thanks for your feedback. I am researching the issue. I'll respond when I have more information.

**Comment by randyurbano** [comment]
I corrected the documentation:

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html#data-api.java-client-library

Please let me know if you have questions or comments. Thanks again for your feedback.
