### ISSUE TITLE
Binlog Retention Hours documentation incorrect

### ISSUE THREAD

**Issue by davidstoker** [awsdocs/amazon-aurora-user-guide#47]
The [Replication documentation](https://github.com/awsdocs/amazon-aurora-user-guide/blob/main/doc_source/AuroraMySQL.Replication.MySQL.md) states the following about using the `mysql.rds_set_configuration` stored procedure to set the number of hours to retain binary logs:

> `CALL mysql.rds_set_configuration('binlog retention hours', 144);`

and 

> If this setting isn't specified, the default for Aurora MySQL is 24 (1 day). If you specify a value for 'binlog retention hours' that is higher than 2160, then Aurora MySQL uses a value of 2160.

If a value like 2160 is used, the following error is thrown:

`For binlog retention hours the value must be between 1 and 168 inclusive or be NULL`

The `rds_set_configuration` stored procedure that sets this value has logic preventing values greater than 168 hours.

```
DELIMITER ;;
CREATE DEFINER=`rdsadmin`@`localhost` PROCEDURE `rds_set_configuration`(IN name VARCHAR(30), IN value INT)
    READS SQL DATA
    DETERMINISTIC
BEGIN
   DECLARE sql_logging BOOLEAN;

   IF name = 'binlog retention hours' AND value NOT BETWEEN 1 AND 168 THEN
       SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'For binlog retention hours the value must be between 1 and 168 inclusive or be NULL';
   END IF;

   SELECT @@sql_log_bin INTO sql_logging;
   SET @@sql_log_bin = OFF;
   UPDATE mysql.rds_configuration
   SET mysql.rds_configuration.value = value
   WHERE BINARY mysql.rds_configuration.name = BINARY name;
   SET @@sql_log_bin = sql_logging;
END;;
DELIMITER ;
```

This was observed on an instance running version `5.7.mysql_aurora.2.09.2`.

Is the documentation here just incorrect or is the RDS provided stored procedure not implemented as intended?

**Comment by randyurbano** [comment]
Thanks for your feedback, and sorry about the delay. We are looking into this issue.

**Comment by max-webster** [comment]
It's a known issue that Aurora MySQL version 2 doesn't have the same higher limit as listed in the documentation. Aurora MySQL version 1 does allow the documented higher limit. The dev team have requested to leave the documentation as-is for the moment, because the preferred action is to update Aurora MySQL version 2 to agree with the doc.

**Comment by max-webster** [comment]
Closing because this is considered a code issue. The limit specified in the doc is the expected/specified behavior.
