### ISSUE TITLE
Aurora serverless v2 private network requirements

### ISSUE THREAD

**Issue by tomiszili** [awsdocs/amazon-aurora-user-guide#67]
Hi!

Needs more explanation if serverless v2 is possible to use in a spoke VPC with only transit gateway routing to the internet (via HUB VPC)?
What subnet settings or vpc endpoints needed to use serverless v2 in this private newtwork? Auto-assign public IPv4 address in a subnet is required?

Thanks.

**Comment by claytran** [comment]
Hi @tomiszili,

Sorry it took us so long to get back to you. You should be able to do this. For more information, see [Scenarios for accessing a DB cluster in a VPC](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_VPC.Scenarios.html) and [Connect VPCs using VPC peering](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-peering.html).

For Serverless v2, you connect to the endpoint of the writer DB instance, and yes, you should auto-assign a public IPv4 address.

I hope this helps,
Clayton

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
