### ISSUE TITLE
Missing release notes for new listed feature

### ISSUE THREAD

**Issue by ronaldbradford** [awsdocs/amazon-aurora-user-guide#78]
I noticed today a new Aurora MySQL release 3.03.1.

However it's not in your release notes. [1]
There is another page I just saw today, and it also must be brand new, as it requires 3.03.1 [2]

I wasn't able to see a current version of docs in order to point out a possible inconsistency.  Is this repo being maintained, i.e. I could not find older 3.0X documents.

Kudos for actually having your docs on VCS. It was a starting point, but it didn't quite help me track this new release+feature.

[1] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.30Updates.html
[2] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.storage-type.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
