### ISSUE TITLE
Documentation for changing capture_plan_baselines is inconsistent

### ISSUE THREAD

**Issue by karlsnyder0** [awsdocs/amazon-aurora-user-guide#79]
When changing `apg_plan_mgmt.capture_plan_baselines` this [doc](https://github.com/awsdocs/amazon-aurora-user-guide/blob/main/doc_source/AuroraPostgreSQL.Optimize.CapturePlans.md#automatically-capturing-plans) states that a reboot is required while this [doc](https://github.com/awsdocs/amazon-aurora-user-guide/blob/main/doc_source/AuroraPostgreSQL.Optimize.Parameters.md#apg_plan_mgmtcapture_plan_baselines) states that a reboot is not required.

Which is it?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
